<?php
/** @package Xpto::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("Administrar_ModuloMap.php");

/**
 * Administrar_ModuloDAO provides object-oriented access to the adm_modulos table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Xpto::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class Administrar_ModuloDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Descricao;


	/**
	 * Returns the foreign object based on the value of Id
	 * @return AdmFuncionalidades
	 */
	public function GetIdAdmFuncionalidades()
	{
		return $this->_phreezer->GetManyToOne($this, "adm_modulos_ibfk_1");
	}


}
?>